### ISSUE TITLE
PATH issue

### ISSUE THREAD

**Issue by wieczorek1990** [lunks/fish-nuggets#15]
Basically [this](https://github.com/lunks/fish-nuggets/blob/master/functions/rvm.fish#l1-10) destroys custom user supplied paths in ~/.config/fish/config.fish.
The quick fix for this is to set PATH after that eval.
Please fix this so that if looks something like that:

``` shell
set PATH $rvm_paths $PATH
```

**Comment by danielpclark** [comment]
Hey @wieczorek1990 if this is still an issue can you suggest where this change is needed for you?  I need more details to move forward with this.  A PR would be helpful as well. I'll close this for now, reopen if the issue persists.
