### ISSUE TITLE
RVM doesn't work under Alpine Linux

### ISSUE THREAD

**Issue by ShogunPanda** [lunks/fish-nuggets#17]
Hi!
I noticed that RVM function doesn't work under Alpine Linux due to a missing argument in the grep execution.

To make it work, simply change line 7 of file fish-nuggets/functions/rvm.fish to this:

```
and eval (grep -E '^rvm|^[^=]*PATH|^GEM_HOME' $env_file | grep -v '_clr=' | sed '/^[^=]*PATH/s/:/" "/g; s/^/set -xg /; s/=/ "/; s/$/" ;/; s/(//; s/)//')
```

Hope this helps!
  Paolo

**Comment by ShogunPanda** [comment]
Closed due to inactivity.

**Comment by danielpclark** [comment]
@ShogunPanda Is this still an issue?  I've been added on as a maintainer and would like to ensure the quality of the code for the best RVM fish-shell experience possible.

**Comment by danielpclark** [comment]
Searching through the history of grep - that's been around for more than 10 years. Beyond that things get harder to find.  I'm going to submit this as a patch.  Thank you for reporting this!

**Comment by danielpclark** [comment]
@ShogunPanda I've noticed your code also doesn't use backslashes in `'^rvm|^[^=]*PATH|^GEM_HOME'` .  For me the code works either way.  Can you verify if the update with just adding the `-E` flag works for you or not?

**Comment by danielpclark** [comment]
I'm installing Alpine Linux to verify if this is an issue.

**Comment by danielpclark** [comment]
Verified this issue with a Docker image (see https://github.com/danielpclark/dev-container-base for case scenario).  @ShogunPanda 's recommendation fixes this perfectly and still works on other OSes.
