### ISSUE TITLE
Fish Shell rvm function assumes that it is installed at .rvm. Breaks for system wide installations.

### ISSUE THREAD

**Issue by NeMO84** [lunks/fish-nuggets#18]
See https://github.com/lunks/fish-nuggets/blob/6b0b28b56ea47e52695a4dc54bb6432d4a84eb61/functions/rvm.fish#L4.

This file is linked directly on https://rvm.io/integration/fish. As such, it should be implementation specific. 

The rvm source file should be based on the existing rvm script file of `~/.rvm/scripts/rvm` or `/usr/local/rvm/scripts/rvm`.

**Comment by danielpclark** [comment]
For me I have RVM in `/usr/share/rvm/bin/rvm`.  The command to get the path to RVM is

```shell
which rvm
```
Which outputs for me `/usr/share/rvm/bin/rvm`.
