### ISSUE TITLE
rvm function messes with my `GOPATH` variable

### ISSUE THREAD

**Issue by yookoala** [lunks/fish-nuggets#24]
I have installed the `rvm` function this April. And I found that `rvm` would mess up my variables unrelated to Ruby installation.

Here is the simplest form of my problem:
```fish
$ set -xg GOPATH /home/foobar/foo:/home/foobar/bar
$ echo $GOPATH
/home/foobar/foo:/home/foobar/bar
$ rvm use default
Using /home/foobar/.rvm/gems/ruby-2.4.1
$ echo $GOPATH
/home/foobar/foo /home/foobar/bar
```

Seems rvm swaps the colon `:` with `\x1E`. Unfortunately, Golang's toolchain needs the variable in its raw form. The rvm function should not assume that all `*PATH` variables need to be converted to fish native array.

Also reported here: fish-shell/fish-shell#4039

**Comment by krader1961** [comment]
This function has a serious bug. These lines are mutating any var that has a `PATH` suffix:

```
  # apply rvm_* and *PATH variables from the captured environment
  and eval (grep -E '^rvm|^[^=]*PATH|^GEM_HOME' $env_file | grep -v '_clr=' | sed '/^[^=]*PATH/s/:/" "/g; s/^/set -xg /; s/=/ "/; s/$/" ;/; s/(//; s/)//')
```

Don't do that. You should not be mutating random "PATH" vars. In fact, you probably shouldn't be mutating Ruby PATH vars in that manner since when they are exported they will end up with the path elements separated by \x1E -- the fish internal array element separator.

**Comment by krader1961** [comment]
Also, note that `echo $GOPATH` does not have a \x1E char between the two path elements as implied by @yookoala's comment. That is a simple space (\x20). However, it is only a simple space in a fish context. The env var inherited by non-fish programs will have the elements separated by \x1E. This happens to be a fish implementation detail with respect to how it handles multi-valued vars (i.e., arrays).

**Comment by lunks** [comment]
@krader1961 I don't use fish anymore so if you want to improve how this is handled, feel free to open up a PR.
