### ISSUE TITLE
Incorrect color code passing from bash to fish

### ISSUE THREAD

**Issue by fjarri** [lunks/fish-nuggets#6]
OSX 10.8.3, fish 2.0 open beta r2, rvm 1.19.1

In rvm.fish, the output of `env` contains several lines like `rvm_notify_clr=<code>` where rvm stores color codes for different messages. When passed to `$env_file`, they are rendered as `^[[...`, and when fish tries to evaluate this (sed'ed) file, the unmatched parentheses produce an error like

```
fish: Tokenizer error: 'Unexpected end of string, parenthesis do not match'
```

Probable solution would be to encode color codes so that fish would understand them, or at least strip them during the creation of `$env_file`. Unfortunately, I do not know about bash and fish enough to fix it myself. I tried removing color codes with `sed` as

```
sed "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g"
```

but it did not seem to work. Any ideas?

**Comment by danielpclark** [comment]
Can you verify this issue still exists with an updated version of fish-shell (`fish -v` = fish, version 2.4.0)?  If so please feel free to reopen the issue.
